### ISSUE TITLE
Old: Define different levels of trust/coordination for signaling 

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/draft-path-signals-collaboration#1]
- Passive/weak/untrusted: spin bit, etc. Minimal information
- (levels in between)
- Fully trusted: TLS handshake, protected content

**Comment by jariarkko** [comment]
This is in the document, but could we be more explicit about it?

Should we add another comment to the doc that the more trust we have, the more information we can share. With authentication you may be able to trust a known entity.

**Comment by jariarkko** [comment]
Leave for next version
