### ISSUE TITLE
Define a new principle on limiting actions based on signals

### ISSUE THREAD

**Issue by mirjak** [intarchboard/draft-path-signals-collaboration#18]
I find that the emphasis on endpoint-to-path signaling as opposed to path-to-endpoint signaling is a missed opportunity.  There's a lot to say about ECN or ICMP signals from the path that is going unaddressed here.  For example:

* How those signals might be validated
* How the sender of those signals might be authenticated
* How actions based on weakly authenticated signals might need to be limited

These considerations apply in both directions (path-to-endpoint and endpoint-to-path).

For example:

For instance, an ICMP error that refers to a valid flow may be more trustworthy than any ICMP error claiming to come from an address.

This assumes a lot.  The point here is that an ICMP signal can often be authenticated as being generated by an on-path entity by virtue of it quoting parts of the IP packet that caused the signal to be generated.  Actions taken as a result are appropriate as long as they are limited to sending of future packets on that path as we assume that path elements are able to refuse to forward a packet.  We might not allow that ICMP signal to tear down connections if those connections might continue elsewhere (path migration as in QUIC), though we might allow that if there is no alternative way to continue (as in TCP without MPTCP).

This is, I think, one of the main components the draft should concentrate on.  That matches some of the other items in the draft: Minimization is good.  Establishing purpose and incentives are also good.  Limiting audience is also good.  More on this last point below, however.

**Comment by tfpauly** [comment]
#27 addresses some of this, but we should consider if we should go further. One way to do this would be to pull out a separate principle for minimizing the effect that a signal is allowed to have (as opposed to just minimizing the information a signal contains) based on the trust/authentication/role of the signal.

**Comment by mirjak** [comment]
might be related to #16
