### ISSUE TITLE
Reconsider consent (MT)

### ISSUE THREAD

**Issue by mirjak** [intarchboard/draft-path-signals-collaboration#19]
I find the focus on consent to be problematic.  The doctrine of consent as it relates to the design of endpoint-path communication seems so far removed from the consciousness of end users that making that association is almost surreal.  My view is that reliance on consent in this setting is highly inappropriate.  Please reconsider your use of this in this document.

**Comment by jariarkko** [comment]
On a call we discussed this with Mirja, Tommy and Jari.

We thought consent as a user thing should largely be outside the scope of the draft. However, there's a related concept that the parties (your browser, the service, a router) need to be in control over what information is shared. 

This is already what the current text mostly talks about.

In some cases that may mean user consent as well but not necessarily. For instance, I use a service that consists of an app and a backend web server. I need to provide user-level consent to the service for everything it does. This may include e.g., sharing some information to further backend systems or with some on-path elements.

**Comment by jariarkko** [comment]
We should rename the section to highlight this focus and review the text to ensure that it is properly explaining this situation.

**Comment by jariarkko** [comment]
I believe we closed this in the -01 version in March
