### ISSUE TITLE
Highlight the difference between e2e and collaborative functions (Toerless)

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#24]
Should highlight the difference between actual e2e functions and collaborative functions such as congestion control (agree, but needs thinking)

**Comment by jariarkko** [comment]
Review needed

**Comment by jariarkko** [comment]
Revert the current change. Expand the discussion in the minimum entities section instead.

**Comment by jariarkko** [comment]
I have a suggested fix now in the file. Please see the diff below. Thoughts, @mirjak and @tfpauly?

<img width="1490" alt="minimum-set-of-entities-examples" src="https://user-images.githubusercontent.com/4134551/151844063-f8b3bf12-cb53-49d8-b9d7-e32c728e3d6a.png">

**Comment by mirjak** [comment]
WFM. Thx!

**Comment by jariarkko** [comment]
Maybe we need to add a sentence about the bigger collaboration.

Also, the principle should be framed around not providing minimum information but rather providing exactly the right information to perform the desired function.

**Comment by jariarkko** [comment]
Where are we on this?

**Comment by mirjak** [comment]
Sorry I didn't realise this was assigned to me. But can't really remember what we wanted to further address...
