### ISSUE TITLE
K2: Review terminology used for "entities" (endpoints, network elements, nodes)

### ISSUE THREAD

**Issue by mirjak** [intarchboard/draft-path-signals-collaboration#30]

**Comment by jariarkko** [comment]
This was also brought up in Robin's review:

In Section 2.6, ensure that we use the same terminology throughout. Robin's comment was: I am confused about the concepts in this chapter: 1. Is the signaling the same as the protocols? 2. Is the on-path signaling the same as the protocols? 3. What is the protocol to carry information? What is the protocol to send and request information? What is the protocol to pass information? I suggest that this concept should be defined clearly before the principle. My understanding 2.5 is not an independent principle. Does it mean the protocol carrying information should comply with the principles 2.4/2.6? If so, why not define the different protocols and signaling before principles and in section 2.4/2.6 explain what protocols and signaling comply with these principles?

**Comment by jariarkko** [comment]
Changes merged, closing issue
