### ISSUE TITLE
RE: Editorial point from Robin

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#59]
. Brackets around 8558 reference in the abstract. (disagree)
   . If the "not" is needed in the abstract. (is needed)
   . Explain the introduction comment about "having to intepret infomration signed for another purpose" better (ok)
   . Expand on why some information is desired in the introduction. (need to think about this)
   . In introduction, s/lead/led/ (ok)
   . Clarify in introdcution, in the lead-to sentence whether the situation or the information is incorrect (ok)
   . Is vs. was in the incomplete-incorrect sentence? (need to check)
   . Ossifying is too abstract, needs an example (perhaps)
   . Captive portals text misses part about them taking over plaintext HTTP sessions (ok)
   . "Controling" => "Controlling" and "again" => "against" in the introduction (ok)
   . After the question list, why is it "all other" and not "all" (need to look at this)
   . What is the "cleanly separated architecture"? (need to look at this)
   . Recommandation => recommendation (ok)
   . Neeeded => needed (ok)
   . Willigness => willingness (ok)
   . Clarify in Section 2.3, Is the protocol mechanism an additional protocol instead of the path signaling? (need to look at this)
   . Senstive => sensitive
   . Check Section 2.5: "The logic may be not right. Definitely there is a distinction between “what” and “how”. Should it be “there is a distinction between what information is passed and what information is carried”?" (our text looks right to me)
   . In Section 2.5, the "actually sent informtation": Does it mean the carried information? (ok)
   . In Section 2.5, clarify this: Request information is naturally different from carrying information. What is difference between sending information and carrying information? (ok, need to look at language to be consistent)
   . In Section 2.5, add an example on what we mean by carrying some information being a requirement for passing traffic through (ok)
   . In Section 2.5: In 2.3, Trust and mutual agreement between the involved entities is also mentioned. Does it has nothing with the 2.3? If it needs to refer to 2.6, why not put 2.5 after 2.6? (need to look at this)
   . In Section 2.5, pass/carry terminology needs to be aligned (ok)
   . In Section 2.6., interations => interactions (ok)
   . In Section 2.6. there's an odd # reference (ok)
   . In Section 2.6: about the "particular information or request": Same issue as the above. The particular information means the possible information like ECN bits which is used for the path signaling. Is request for another protocol? (need to look at this)
   . vulernabilities => vulnerabilities (ok)
   . decide whether to use signalled or signaled (ok)

**Comment by mirjak** [comment]
Mirja to review PR #70

**Comment by jariarkko** [comment]
Jari has a proposal, Mirja to review

**Comment by jariarkko** [comment]
Edits merged in. Closing issue.
