### ISSUE TITLE
M1: Shift tone to fighting pervasive monitoring

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#60]
From Mallory:

Do more to shift the tone of the document to actually improving upon, deepening and iterating on what RFC7258 says, e.g., on where signals mitigate or do not worsen PM situation; talk more about privacy - signals (non-)tradeoff, highlight the point about intentionality being key and being good for network management.

**Comment by jariarkko** [comment]
Seems reasonable.. need to see/craft text.

**Comment by hardie** [comment]
Propose to add text to this "Taken together, these principles focus on the inherent privacy and security concerns of sharing information between endpoints and network elements, emphasizing that careful scrutiny and a high bar of consent and trust need to be applied.", to highlight that the presence of PM that this is key work.

**Comment by jariarkko** [comment]
Changes merged, closing issue
