### ISSUE TITLE
M3: Is there assumed symmetry between NEs and EPs?

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#62]
From Mallory:

Why do we assume symmetry between network elements and endpoints?

**Comment by jariarkko** [comment]
Good question, may need more text/thinking.

**Comment by hardie** [comment]
We agree that each may have the need to communicate with the other, but that this may be the limit of the symmetry.

**Comment by jariarkko** [comment]
Proceeded to apply this PR as a simple change
