### ISSUE TITLE
M4: Question / principle better alignment

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#63]
From Mallory: 

I'm noting that the principles reflect almost exactly the questions on Page 5. Maybe a tighter conceptual structure would make those identical mirrors of one another.

**Comment by jariarkko** [comment]
Ok.. needs to be looked at.

**Comment by hardie** [comment]
We agree that each may have the need to communicate with the other, but that this may be the limit of the symmetry.

**Comment by jariarkko** [comment]
We agree.. needs edits

**Comment by jariarkko** [comment]
Is this possible solved by Mirja's previous work, and the extra question that I added as part of PR Suggested-resolution-issue-61? Mirja you should check..

**Comment by jariarkko** [comment]
This is still pending, see also our discussion re issue #61. I'm fine if the first principle has no matching question...
