### ISSUE TITLE
M6: Future work suggestions (DDoS part)

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#65]
From Mallory:

   .  DDoS-- there might be a tension here with increased censorship capabilities that could be treated. Ie if you can more easily block DDoS with signals, couldn't you more easily block other things, too.

**Comment by jariarkko** [comment]
All good comments.

**Comment by jariarkko** [comment]
Tommy and Ted to address DDoS. Jari to look at if anything is needed for the others.  Some, like net neutrality are complex topics that we might better not get into too much -- except parhaps referring to it as related.

**Comment by jariarkko** [comment]
Redefined this issue as only about DDoS.

**Comment by mirjak** [comment]
Tommy is on holidays until July 16th.

From: hardie ***@***.***>
Reply to: intarchboard/draft-path-signals-collaboration ***@***.***>
Date: Monday, 11. July 2022 at 17:55
To: intarchboard/draft-path-signals-collaboration ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [intarchboard/draft-path-signals-collaboration] M6: Future work suggestions (DDoS part) (Issue #65)

I sent an email to Tommy (cc'ing you and Mirja), but I haven't seen
anything back.

**Comment by hardie** [comment]
I mis-marked this, but see
https://github.com/intarchboard/draft-path-signals-collaboration/pull/86
for a proposed resolution.

Ted

**Comment by jariarkko** [comment]
PR 86 is about multiparty communication, I think ... how I read it at least. Is there something on DDoS?

**Comment by jariarkko** [comment]
I’ve created a PR for a small change wrt to Section 3 on this.

https://github.com/intarchboard/draft-path-signals-collaboration/pull/87

Text:

* The use of path signals for reducing the effects of
   denial-of-service attacks, e.g., perhaps modern forms of "source
   quench" designs could be developed. The difficulty is finding a solution
   that would be both effective against attacks and would not enable third
   parties from slowing down or censoring someone else's commmunication.

But I have run out of time; I will merge this in and ship the draft after some reorg (I need to do the reorder change now, manually).

If there’s something that’s not right, we can make further draft versions…
