### ISSUE TITLE
Vittorio: Vagueness around consent

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#89]
“I do not have specific text suggestions, but I noted some kind of vagueness around consent, i.e. in the subjects of sentences like "The sender needs to agree to sending the information" - who is the sender, the application or the user? One thing is the agreement of the client application that will share information, i.e. of its developer, and another is the agreement of the user that will be sitting in front of that application and entering their information into it.
 
There is a paragraph in 2.2 discussing this, but it only mentions the case in which the application would like to collect information "against" the user, not other cases which may appear, such as legal compliance. Also, it makes some blanket statements that are really too broad, such as "Information that directly relates to the user should not be shared without the user's consent" - there are a cases in which user consent is not legally necessary nor even possible, but applications will be required to share that information anyway. I would just refer to applicable privacy legislation, declaring this out of scope.”

It is unclear to me what we should do about this. But I think we were vague to some extent on purpose here.

See https://mailarchive.ietf.org/arch/msg/architecture-discuss/k4npcAf_EcbpP1Dp8OY1cDwFE8c/

**Comment by jariarkko** [comment]
The user never sends or does anything; it is always app code underneath. But maybe we should say

  ... sender needs to decide that it wants to send information ...

**Comment by hardie** [comment]
Agreed to change to "decide that it wants to send information".  Mirja will add text in PR.

**Comment by hardie** [comment]
I'm okay with this.  I think it would work very slightly better as:

The sender should have an option to decide whether it wants to send the information
to a specific entities or set of entities.
