### ISSUE TITLE
Vittorio: User should be able to choose which network or entity receives information

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#90]
“On the other hand, perhaps in 2.2 there should be some language suggesting that the user should be able to pick the network entity that they want their explicit signals to reach, whenever this makes sense. Sometimes the signal can only be directed to a specific entity (e.g. congestion-related signals can only be directed to the specific network you are using) but in some others signals can be directed to one of multiple providers (e.g. DNS resolution). In this case, consent should not just be about sharing the data, but about which specific party to involve.”

I’m not sure this is in scope. The draft should not be about general configuration of things, e.g., DNS resolvers, or which networks to use.

See https://mailarchive.ietf.org/arch/msg/architecture-discuss/k4npcAf_EcbpP1Dp8OY1cDwFE8c/

**Comment by hardie** [comment]
Out of scope for this document, though a similar point might be incorporated into a document working through an example like DNS or congestion control.
