### ISSUE TITLE
Chris: Timing. All cleartext is gone before any of this can be deployed

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#91]
”It will take many years to
develop and deploy new information-sharing protocols that follow these
principles. In the meantime, hiding of cleartext path signals continues
apace. Network operators therefore face a few years of enforced blindness
before the new mechanisms are in place to permit sharing where the user
desires it. So it would be helpful to (a) advise careful consultation
before withdrawing each cleartext signal, and (b) work quickly on
developing the new protocols.”

Thoughts?

See https://mailarchive.ietf.org/arch/msg/architecture-discuss/_14RT-XdZ1aqk6Kb522kNe548xA/

**Comment by hardie** [comment]
The authors agree that it will take a number of years to develop and deploy protocols that follow these principles, but the authors do not agree that cleartext signals should be retained during the development period.  The incentives for deployment of new protocol mechanisms would be quite weak while cleartext signals are retained. In addition, some of these signals represent security and privacy concerns which have been extensively documented.
