### ISSUE TITLE
Chris: Examples for intro

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#92]
See https://mailarchive.ietf.org/arch/msg/architecture-discuss/_14RT-XdZ1aqk6Kb522kNe548xA/

**Comment by jariarkko** [comment]
”*Section 1: Introduction*

The current document says "But a lack of all path signalling, on the other
hand, may be harmful to network management, debugging, or the ability for
networks to provide the most efficient services."

I’d like to suggest some more real-life examples in there, so it becomes
two sentences:
"But a lack of all path signalling, on the other hand, may be harmful to
network management, debugging, service provision, or security. It can also
harm the ability of networks to provide the most efficient services,
including traffic routing and content delivery optimisation.””

I think ok.

**Comment by hardie** [comment]
Tentative update "But a lack of all path signalling, on the other hand, may be harmful to network management, debugging, or the ability for networks to provide the most efficient services." to "But a lack of all path signalling, on the other hand, may limit network management, debugging, or the ability for networks to optimize their provision of services."
