### ISSUE TITLE
Chris: Principles ordering

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#94]
See https://mailarchive.ietf.org/arch/msg/architecture-discuss/_14RT-XdZ1aqk6Kb522kNe548xA/

**Comment by jariarkko** [comment]
”*Section 2: Principles*

These are listed in a counter-intuitive order for me. I would prefer an
order that aligns with the thought process someone would need to go through
in order to arrive at the right answer in an efficient way. I think you
have to first define the minimal information to be sent and who it needs to
be sent to, before considering how that should be achieved. I therefore
propose this is a better order:

Minimize Information
Limiting Impact of Information
Minimum Set of Entities
Intentional Distribution
Control of the Distribution of Information
Protecting Information and Authentication
Carrying Information


But people may be able to point out areas where some of these should be
swapped.”

Thoughts?

**Comment by hardie** [comment]
Closed to maintain the order suggested by Mirja.
