### ISSUE TITLE
Chris: Missing principle on flow identification?

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-path-signals-collaboration#95]
See https://mailarchive.ietf.org/arch/msg/architecture-discuss/_14RT-XdZ1aqk6Kb522kNe548xA/

**Comment by jariarkko** [comment]
“*Section 2’s missing principle?*

The document implies there are cases where some flows should be
identifiable to an authorised network element. But it says nothing about
how the packets comprising the flow can be identified. The classic way to
identify a flow is by 5-tuple, but this is weakening and the use of MASQUE
destroys it entirely. I know the task of protocol design to support
specific use cases is left to the reader, but it might be beneficial to
articulate a generic principle that designers can draw on.”

Thoughts?

**Comment by hardie** [comment]
The author team believes that the information about which packets are part of the flow is itself a path signal. The overarching principle to minimize information is thus the over-riding principle here.  This requires protocol specific analysis of any flow-identifying signal.

Mirja to look for a place in the document to make the point that the identification of which packets are part of the flow is a path signal.

**Comment by hardie** [comment]
The current PR says:  "This applies to information sent by an
application about itself, information sent about users, or information
sent by the network and it also includes information
that can be used to associate packets to a flow or user context. "

I think this is basically the right placement and concept, but I think we might want to reword it (or let the RFC Editor help us reword it one step on).   Here's a very slight edit:

This applies to information sent by an
application about itself, information sent about users, or information
sent by the network.  This applies even to information
that can be used to associate packets to a flow or user context.
